In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1869, 6621, 4294, 1285],
 [1869, 6621, 4294, 9000],
 [1869, 7702, 4294, 933],
 [7496, 589, 7906, 5053, 6995],
 [7496, 589, 7906, 5053, 4867],
 [2913, 1869, 2402, 4294, 9632],
 [6133, 9291, 4869, 5053]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1869 6621 4294 1285]
 [   0    0    0    0 1869 6621 4294 9000]
 [   0    0    0    0 1869 7702 4294  933]
 [   0    0    0 7496  589 7906 5053 6995]
 [   0    0    0 7496  589 7906 5053 4867]
 [   0    0    0 2913 1869 2402 4294 9632]
 [   0    0    0    0 6133 9291 4869 5053]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 98ms/step


array([[[-3.37497965e-02,  1.18831284e-02,  6.17436320e-03,
         -4.51373458e-02, -2.62860302e-02,  4.61126231e-02,
          1.23946555e-02, -4.83187549e-02,  3.20560820e-02,
         -3.20449844e-02],
        [-3.37497965e-02,  1.18831284e-02,  6.17436320e-03,
         -4.51373458e-02, -2.62860302e-02,  4.61126231e-02,
          1.23946555e-02, -4.83187549e-02,  3.20560820e-02,
         -3.20449844e-02],
        [-3.37497965e-02,  1.18831284e-02,  6.17436320e-03,
         -4.51373458e-02, -2.62860302e-02,  4.61126231e-02,
          1.23946555e-02, -4.83187549e-02,  3.20560820e-02,
         -3.20449844e-02],
        [-3.37497965e-02,  1.18831284e-02,  6.17436320e-03,
         -4.51373458e-02, -2.62860302e-02,  4.61126231e-02,
          1.23946555e-02, -4.83187549e-02,  3.20560820e-02,
         -3.20449844e-02],
        [-2.33522188e-02, -8.80109146e-03,  1.33529343e-02,
         -3.38342190e-02,  2.06928514e-02,  3.65377702e-02,
          3.37709673e-02,  3.79402898e-02, -4.847301

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 1869, 6621, 4294, 1285])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 57ms/step


array([[-0.0337498 ,  0.01188313,  0.00617436, -0.04513735, -0.02628603,
         0.04611262,  0.01239466, -0.04831875,  0.03205608, -0.03204498],
       [-0.0337498 ,  0.01188313,  0.00617436, -0.04513735, -0.02628603,
         0.04611262,  0.01239466, -0.04831875,  0.03205608, -0.03204498],
       [-0.0337498 ,  0.01188313,  0.00617436, -0.04513735, -0.02628603,
         0.04611262,  0.01239466, -0.04831875,  0.03205608, -0.03204498],
       [-0.0337498 ,  0.01188313,  0.00617436, -0.04513735, -0.02628603,
         0.04611262,  0.01239466, -0.04831875,  0.03205608, -0.03204498],
       [-0.02335222, -0.00880109,  0.01335293, -0.03383422,  0.02069285,
         0.03653777,  0.03377097,  0.03794029, -0.04847301, -0.00736069],
       [-0.02085879, -0.02961944,  0.04917746,  0.03437856,  0.00564288,
         0.033997  ,  0.03581944,  0.00136054, -0.04758511,  0.04135069],
       [-0.00701666, -0.01935582,  0.01285747, -0.00344604, -0.01832298,
         0.01798657,  0.04865081, -0.04140071